#@ load("@ytt:data", "data")
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-awesome-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: #@ "https://{GIT_HOST}/myapp.git".format(**data.values)
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true