---
kind: Secret
apiVersion: v1
metadata:
  name: git-credentials
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://<hostname>"]
      helper = store
  .git-credentials: |
    https://<user>:<pass>@<hostname>