#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  annotations:
    tekton.dev/docker-0: #@ "{REGISTRY_HOST}".format(**data.values)
type: kubernetes.io/basic-auth
stringData:
    username: #@ "{REGISTRY_USERNAME}".format(**data.values)
    password: #@ "{REGISTRY_PASSWORD}".format(**data.values)
--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-login
secrets:
  - name: docker-secret
