apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "cicd"
spec:
  title: "CICD fundamentals"
  description: "Learn the fundamentals of CICD"
  url: https://github.com/GlobeTeam-Platform/ga-kursus-cicd
  difficulty: beginner
  duration: 3h
  vendor: 12f.dk
  authors:
    - Robert Jensen
  tags:
    - gitops
    - devops
    - argocd
    - Dagger
    - kubernetes
  publish:
    image: "$(image_repository)/ga-kursus-cicd-files:$(workshop_version)"
  workshop:
    files:
    - image:
        url: $(image_repository)/ga-kursus-cicd-files:$(workshop_version)
      includePaths:
      - /workshop/**
      - /exercises/**
      - /templates/**
      - /install/**
      - /README.md
  session:
    namespaces:
      budget: high
    applications:
      slides:
        enabled: true
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      console:
        enabled: false
      docker:
        enabled: true
      registry:
        enabled: true
      git:
        enabled: true
      vcluster:
        enabled: true
        objects:
        - apiVersion: v1
          kind: Secret
          metadata:
            name: git-credentials
          type: Opaque
          stringData:
            .gitconfig: |
              [credential "$(git_protocol)://$(git_host)"]
                helper = store
            .git-credentials: |
              $(git_protocol)://$(git_username):$(git_password)@$(git_host)
        - apiVersion: v1
          kind: Secret
          metadata:
            name: docker-secret
            annotations:
              tekton.dev/docker-0: $(REGISTRY_HOST)
          type: kubernetes.io/basic-auth
          stringData:
              username: $(REGISTRY_USERNAME)
              password: $(REGISTRY_PASSWORD)
        - apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: docker-login
          secrets:
            - name: docker-secret
    #ingresses:
    #- name: app
    #  protocol: http
    #  host: my-awesome-app.$(session_namespace).svc.$(cluster_domain)
    #  port: 80
    dashboards:
    - name: ArgoCD
      url: "$(ingress_protocol)://argocd-$(session_name).$(ingress_domain)"
    - name: my-awesome-app
      url: "$(ingress_protocol)://my-awesome-app-$(session_name).$(ingress_domain)"
    #- name: Tekton
    #  url: "$(ingress_protocol)://tekton-$(session_name).$(ingress_domain)"


